
name: Seed and Commit Db

on:
  schedule:
    - cron: "*/2 * * * *"
permissions:
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
            npm run seed
            git config --global Vivek Patel 
            git config --global vpat95@users.noreply.github.com 
            git commit -am "Seed Data"
            git push
