# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

on:
  schedule:
    - cron: '5 6-21 * * *'
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm run seed
          git config --global Vivek patel 'Your Name'
          git config --global vpat95@users.noreply.github.com
          git commit -am "Seed DB"
          git push
